namespace SpaceInvaders.FontSystem
{
    public enum FontName
    {
        GameOverLabel,
        Test,
        NullObject,
        Uninitialized,
        TopBar,
        ScoreOne,
        ScoreTwo,
        ScoreOneLabel,
        ScoreTwoLabel,
        HighScoreLabel,
        HighScore,
        IntroLabel,
        LifeCount,
        CreditLabel,
        CreditCount,
        AttractPlay,
        AttractSpace,
        AttractInvaders,
        SAT,
        UFOLine,
        OctoLine,
        CrabLine,
        SquidLine,
        AttractPush
    }
}
